//
// Generated file, do not edit! Created by nedtool 5.6 from myPacket.msg.
//

#ifndef __MYPACKET_M_H
#define __MYPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>myPacket.msg:17</tt> by nedtool.
 * <pre>
 * packet MyPacket
 * {
 *     simtime_t initTime;
 *     int flowId;
 *     int flowSeqNum;
 *     int linkSeqNum;
 *     int hopCount = 0;
 * 
 * }
 * </pre>
 */
class MyPacket : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t initTime;
    int flowId;
    int flowSeqNum;
    int linkSeqNum;
    int hopCount;

  private:
    void copy(const MyPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyPacket&);

  public:
    MyPacket(const char *name=nullptr, short kind=0);
    MyPacket(const MyPacket& other);
    virtual ~MyPacket();
    MyPacket& operator=(const MyPacket& other);
    virtual MyPacket *dup() const override {return new MyPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getInitTime() const;
    virtual void setInitTime(::omnetpp::simtime_t initTime);
    virtual int getFlowId() const;
    virtual void setFlowId(int flowId);
    virtual int getFlowSeqNum() const;
    virtual void setFlowSeqNum(int flowSeqNum);
    virtual int getLinkSeqNum() const;
    virtual void setLinkSeqNum(int linkSeqNum);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MyPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MyPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MYPACKET_M_H

